version: "3.9"
name: mem0-dev

services:
  mem0:
    build:
      context: ..  # Set context to parent directory
      dockerfile: server/dev.Dockerfile
    ports:
      - "8888:8000"
    env_file:
      - .env
    networks:
      - mem0_network
    volumes:
      - ./history:/app/history      # History db location. By default, it creates a history.db file on the server folder
      - .:/app                      # Server code. This allows to reload the app when the server code is updated
      - ../mem0:/app/packages/mem0  # Mem0 library. This allows to reload the app when the library code is updated
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    depends_on:
      qdrant:
        condition: service_started
      memgraph:
        condition: service_started
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload  # Enable auto-reload
    environment:
      - PYTHONDONTWRITEBYTECODE=1  # Prevents Python from writing .pyc files
      - PYTHONUNBUFFERED=1  # Ensures Python output is sent straight to terminal
      - CHAT_API_BASE=${CHAT_API_BASE:-https://api.openai.com/v1}
      - CHAT_API_KEY=${CHAT_API_KEY:-}
      - CHAT_MODEL=${CHAT_MODEL:-gpt-4o}

  qdrant:
    image: qdrant/qdrant
    networks:
      - mem0_network
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
  memgraph:
    image: memgraph/memgraph-platform
    networks:
      - mem0_network
    ports:
      - "7687:7687"
    volumes:
      - memgraph_data:/var/lib/memgraph

volumes:
  qdrant_data:
  memgraph_data:

networks:
  mem0_network:
    driver: bridge